version: '3.9'

services:
  storage:
    image: openzipkin/zipkin-mysql:latest
    container_name: mysql-home-stuff-backed
    networks:
      - zipkin-red

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin-home-stuff-backed
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=storage
      # Add the baked-in username and password for the zipkin-mysql image
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
    depends_on:
      - storage
    networks:
      - zipkin-red

  dependencies:
    image: openzipkin/zipkin-dependencies:latest
    container_name: dependencies-home-stuff-backed
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=storage
      # Add the baked-in username and password for the zipkin-mysql image
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
      - JAVA_OPTS=-verbose:gc -Xms1G -Xmx1G
    depends_on:
      - storage
    networks:
      - zipkin-red

  postgres-keycloak:
    container_name: postgres-keycloak-home-stuff-backed
    image: postgres:15-alpine3.19
#    ports:
#      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=keycloak
    networks:
      - keycloak-red

  keycloak:
    container_name: keycloak-home-stuff-backed
    image: quay.io/keycloak/keycloak:23.0.6
    ports:
      - "9090:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLE=true
      - KC_METRICS_ENABLE=true
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres-keycloak
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=admin
    command: start-dev
    networks:
      - keycloak-red
    depends_on:
      - postgres-keycloak

  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb-home-stuff-backed'
    environment:
      - 'MONGO_INITDB_DATABASE=nourishment'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
    ports:
      - '27017:27017'
    networks:
      - 'mongodb-red'

networks:
  keycloak-red:
    driver: bridge
  zipkin-red:
    driver: bridge
  mongodb-red:
    driver: bridge