server:
  port: 8083
spring:
  webflux:
    base-path: /products/v0
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: false

management:
  tracing:
    enabled: false
#    sampling:
#      probability: 1.0
#  endpoints:
#    web:
#      exposure:
#        include: prometheus
#  metrics:
#    distribution:
#      percentiles-histogram:
#        http:
#          server:
#            requests: true

mongodb:
  connecting:
    string: mongodb://root:secret@localhost:27017
  database:
    name: nourishment