server:
  port: 8083
spring:
  webflux:
    base-path: /api/v0
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true


mongodb:
  connecting:
    string: ${MONGODB_CONNECTION_STRING:mongodb://root:secret@localhost:27017}
  database:
    name: ${MONGODB_DATABASE_NAME:nourishment}